spring.application.name=ecommerce-site

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

#spring.application.name=ecommerce-site
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce-site
#spring.datasource.username=postgres
#spring.datasource.password=rajareddy@123
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#jwt.secret=rajaecommerce998aaaaaasssuuuuwwsitesecretkey4259
#jwt.expiration=86400000